### ISSUE TITLE
Generate QR code in terminal for quicker copying URL to phone

### ISSUE THREAD

**Issue by harshilsharma63** [yusuf8ahmed/Ship#1]
You can use something like this - https://github.com/lincolnloop/python-qrcode/issues/61

**Comment by yusuf8ahmed** [comment]
Thanks, this will be in version v0.0.1.7

**Comment by yusuf8ahmed** [comment]
Thanks, this will be in version v0.0.1.7

**Comment by yusuf8ahmed** [comment]
QR codes support is now available
