### ISSUE TITLE
[enhancement] implement pytest as testing framework

### ISSUE THREAD

**Issue by EsbenLorenzen** [yusuf8ahmed/Ship#2]
Hi,

First off all, great project.

I see on the Projects-board, that automated testing seems to be in progress. Are you currently working on this?

If not, I would like to offer my help with implementing testing using pytest.

Also, have you decided on a license for this project? I would like to contribute, if you are looking for any help.

**Comment by yusuf8ahmed** [comment]
I have never used pytest and any help would be appreciated

**Comment by EsbenLorenzen** [comment]
I will take a shot at it tomorrow or sunday.

**Comment by yusuf8ahmed** [comment]
👍👍👍

**Comment by EsbenLorenzen** [comment]
@yusuf8ahmed 
So something has come up over the weekend, which will take up the majority of my free time in the coming weeks.
I won't be able to work on this issue, so you might want to take a shot at it yourself, or hope someone else jumps in.

I'll keep subscribing to issues, to see if there are any smaller stuff I can give a hand to.

**Comment by yusuf8ahmed** [comment]
👍👍👍

**Comment by yusuf8ahmed** [comment]
Thanks for opening the issue, This bug was fixed and should be in release alpha 0.0.4.0 #3 #5
