### ISSUE TITLE
Filepaths not beginning with a slash are unable to be downloaded

### ISSUE THREAD

**Issue by CyberFoxar** [yusuf8ahmed/Ship#3]
Hello, love the app concept.

However, on windows there's a problem with the downloading of files, related to how to filepaths are handled both on the web browser and in internals. 

On windows, filepaths begins with a letter, and not a forward slash. This confuses your templates and links become invalid.

Example:
Say our file is at this path in windows: `E:/A-folder/picture.jpg`
This is a valid Powershell-style path, as well as a pythonic one (though it is not a valid CMD one, that would be `E:\A-folder\picture.jpg`, which also has problems not related to this issue)
I then invoke ship using: `ship -o 'E:/A-folder/picture.jpg'`. Ship launches, all good. However, in the resulting HTML page, the preview, as well as the link don't work, because they're not valid HTML root-relative links !
Here's what you see in the HTML: 
```HTML
<button id="shipbutton">
        <a href="E:/A-folder/picture.jpg" style="text-decoration: none; color: white;" download="">
            <p>Ship It</p>
        </a>
</button>
```
While the `href` should begin with a forward slash `/`, i.e. `/E:/A-folder/picture.jpg`, which is a valid link that downloads the picture as expected.

## Update by Chromaz
Refer to issue #5

**Comment by yusuf8ahmed** [comment]
bug and comment moved #5 to reduce due to redundancy
