### ISSUE TITLE
[enhancement] Clean up unused dependencies from requirements.txt

### ISSUE THREAD

**Issue by EsbenLorenzen** [yusuf8ahmed/Ship#4]
It seems like there is a lot of dependencies listed in requirements.txt, which are not being used. Probably from early development.

Did a quick scan-through, and these dependencies seems to be removable, without any issues:

- aiofiles==0.5.0
- autopep8==1.5.3
- bleach==3.1.5
- certifi==2020.6.20
- chardet==3.0.4
- colorama==0.4.3
- docutils==0.16
- future==0.18.2
- h11==0.9.0
- h2==3.2.0
- hpack==3.0.0
- hstspreload==2020.6.23
- httptools==0.1.1
- httpx==0.11.1
- hyperframe==5.2.0
- idna==2.10
- importlib-metadata==1.7.0
- keyring==21.2.1
- multidict==4.7.6
- packaging==20.4
- pkginfo==1.5.0.1
- psutil==5.7.0
- pycodestyle==2.6.0
- Pygments==2.6.1
- pyparsing==2.4.7
- PyYAML==5.3.1
- readme-renderer==26.0
- requests==2.24.0
- requests-toolbelt==0.9.1
- sanic==20.3.0
- six==1.15.0
- sniffio==1.1.0
- toml==0.10.1
- tornado==6.0.4
- tqdm==4.47.0
- twine==3.2.0
- ujson==3.0.0
- urllib3==1.25.9
- uvloop==0.14.0
- webencodings==0.5.1
- websockets==8.1
- zipp==3.1.0

What I'm left with is:
- loguru==0.5.1
- Pillow==7.1.2
- pyngrok==4.1.3
- qrcode==6.1

I am able to run all tests and ship files across devices without any issues after making the reduction in dependencies.

**Comment by yusuf8ahmed** [comment]
Thanks for the issue. everything should be correct now
